import { describe, expect, it } from "vitest";

import { composeReadme, createCreatePlan, defineModule } from "./index.js";

describe("composeReadme", () => {
  it("renders a deterministic stack-aware README with the required sections", () => {
    const modules = [
      defineModule({
        id: "web/nextjs",
        version: "1.0.0",
        title: "Next.js",
        description: "Web app",
        readme: {
          stack: ["Next.js"],
          layout: [{ path: "apps/web", description: "Next.js web app" }],
          prerequisites: ["Node.js 22"],
          installCommands: [{ label: "Install dependencies", command: "pnpm install" }],
          devCommands: [{ label: "Web dev", command: "pnpm dev" }],
          verificationCommands: [{ label: "Typecheck", command: "pnpm typecheck" }],
          commands: [{ label: "Build", command: "pnpm build" }],
          stackkit: ["Generated by Stackkit."]
        }
      }),
      defineModule({
        id: "api/fastapi",
        version: "1.0.0",
        title: "FastAPI",
        description: "API service",
        readme: {
          stack: ["FastAPI"],
          layout: [{ path: "apps/api", description: "FastAPI service" }],
          prerequisites: ["uv"],
          devCommands: [{ label: "API tests", command: "pnpm --dir apps/api test" }],
          verificationCommands: [{ label: "API runtime tests", command: "pnpm --dir apps/api exec uv run pytest" }]
        },
        envVars: [
          {
            name: "DATABASE_URL",
            description: "Database connection string.",
            required: true,
            example: "",
            target: "api"
          }
        ]
      })
    ];

    const readme = composeReadme({ projectName: "acme", packageManager: "pnpm", modules });

    expect(readme).toContain("# acme");
    expect(readme).toContain("- Next.js");
    expect(readme).toContain("`apps/api` - FastAPI service");
    expect(readme).toContain("## Environment");
    expect(readme).toContain("| API | `DATABASE_URL` | Required | Database connection string. |");
    expect(readme).toMatch(
      /# acme\n\n## Stack\n[\s\S]*## Project Layout\n[\s\S]*## Prerequisites\n[\s\S]*## Install\n[\s\S]*## Development\n[\s\S]*## Verification\n[\s\S]*## Commands\n[\s\S]*## Environment\n[\s\S]*## Stackkit/
    );
  });

  it("plans a generated README for create output", () => {
    const plan = createCreatePlan({
      config: {
        projectName: "acme",
        packageManager: "pnpm",
        workspace: "pnpm-turbo",
        modules: ["web/nextjs"],
        ai: { skillTargets: ["codex"] }
      },
      availableModules: [
        defineModule({
          id: "web/nextjs",
          version: "1.0.0",
          title: "Next.js",
          description: "Next.js web application",
          readme: {
            stack: ["Next.js"],
            layout: [{ path: "apps/web", description: "Next.js web app" }]
          }
        })
      ]
    });

    expect(plan.filePlan.files).toEqual(
      expect.arrayContaining([
        expect.objectContaining({
          path: "README.md",
          owner: "docs/readme",
          content: expect.stringContaining("# acme")
        })
      ])
    );
  });
});
